# Generated by Django 6.0.3 on 2026-04-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_estimated_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scratchcard',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Auto-generated coupon code after scratch', max_length=20),
        ),
        migrations.AlterField(
            model_name='scratchcard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scratchcard',
            name='reward_value',
            field=models.PositiveIntegerField(default=10, help_text='Value: 10 = 10% or ৳10 or 50XP'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, help_text="User's unique referral code", max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='scratch_cards',
            field=models.PositiveIntegerField(default=0, help_text='Unscratched cards available'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text='Experience points'),
        ),
        migrations.AlterField(
            model_name='xplog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
